# Generated by Django 5.2 on 2025-05-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorites_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='food_id',
        ),
    ]
