# Generated by Django 5.2 on 2025-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_favorites_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='food_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
